groups:
  - name: InstanceDown
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: 'critical'
        annotations:
          summary: 'Instance {{ $labels.instance }} down'
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'

      - alert: HighCpuUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 90
        for: 2m
        labels:
          severity: 'warning'
        annotations:
          summary: 'High CPU usage on {{ $labels.instance }}'
          description: '{{ $labels.instance }} has had CPU usage above 90% for more than 2 minutes.'

      - alert: NginxDown
        expr: nginx_up{job="nginx"} == 0
        for: 1m
        labels:
          severity: "critical"
        annotations:
          summary: "Nginx is down on {{ $labels.instance }}"
          description: "The Nginx service is not responding. Ansible restart required."
