global:
  scrape_interval: 10s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['<web-server-private-ip>:9113']

  - job_name: 'node_exporter_web_server'
    static_configs:
      - targets: ['<web-server-private-ip>:9100']

